name: Tag from Maven Version

on:
  workflow_dispatch: # dÃ©clenchement manuel uniquement

permissions:
  contents: write

jobs:
  tag-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Get Maven project version
        id: get_version
        run: |
          mvn $MAVEN_CLI_OPTS build-helper:parse-version versions:set@release
          VERSION=$(mvn $MAVEN_CLI_OPTS help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add pom.xml
          git commit -m "build(release): Version $VERSION"
        env:
          MAVEN_CLI_OPTS: ${{ env.MAVEN_CLI_OPTS }}

      - name: Create Git tag
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          echo "Tag to create: $TAG"
          git tag $TAG
          git push origin $TAG

      - name: Next Development Version
        run: |
          git reset --head HEAD^
          mvn $MAVEN_CLI_OPTS build-helper:parse-version versions:set@minor
          VERSION=$(mvn $MAVEN_CLI_OPTS help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION"
          git add pom.xml
          git commit -m "build(development): Next Development Version $VERSION"
        env:
          MAVEN_CLI_OPTS: ${{ env.MAVEN_CLI_OPTS }}